kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80   # Map HTTP
        hostPort: 80
      - containerPort: 443  # Map HTTPS (optional)
        hostPort: 443
      - containerPort: 30001  # Map HTTPS (optional)
        hostPort: 3001
      - containerPort: 30007  # Map HTTPS (optional)
        hostPort: 3007
      - containerPort: 30080  # Map HTTPS (optional)
        hostPort: 3008
